/*
  DESTINADO PARA ENCONTRAR O NOME CORRETO DO BUCKET DE FOTOS
  - "DEFAULT_ENV_BUCKET_PHOTO" É O NOME DA VARIÁVEL DE AMBIENTE QUE GUARDARÁ
    O NOME CORRETO DO BUCKET A SER USADO PARA SALVAR AS FOTOS.

  - "DEFAULT_BUCKET_PHOTO" É O NOME DO BUCKET A SER USADO SE O MESMO NÃO ESTIVER
    CORRETAMENTE SETADO NA VARIAVEL DE AMBIENTE.

  !!VALE LEMBRAR QUE TODA A APLICAÇÃO E/OU LAMBDAS/SERVERLESS FRAMEWORD IRÃO
  UTILIZAR DESTE ARQUIVO DE CONFIGURAÇÃO, ENTÃO DEVE SER CONFIGURADO ANTES DO
  DEPLOY INICIAL!

  OBS: ESTA CONFIGURAÇÃO TAMBEM SE DESTINA A CONFIGURAÇÃO DO NOME DA TABELA DO
  BANCO DE DADOS, UTILIZANDO ASSIM DA MESMA SEMELHANÇA DA FORMA QUE FOI CRIADO O
  BUCKET, PARA QUE O SISTEMA POSSA SER INICIADO DENTRO DE QUALQUER CONTA SEM QUE
  O MESMO TENHA PROBLEMAS COM OUTROS BUCKETS OU TABELAS CRIADAS, ASSIM PODENDO
  SER ESCOLHIDO ANTES DO START E INSTALAÇÃO DO SISTEMA.
*/

/* BUCKET DE FOTOS */
const DEFAULT_ENV_BUCKET_PHOTO = 'BUCKET_PHOTO';
const DEFAULT_BUCKET_PHOTO = 'kelvintccbucket';

/* TABELA DYNAMODB PARA REGISTRO DE OCORRÊNCIAS*/
const DEFAULT_ENV_DB_OCCURRENCE = 'DB_OCCURRENCE';
const DEFAULT_DB_OCCURRENCE = 'kelvintccdynamo';

module.exports.location = () => {
  return {
    bucketPhoto: getBucketPhoto(),
    tableOccurrence: getTableOccurrence()
  }
}

function getBucketPhoto(){
  return process.env[DEFAULT_ENV_BUCKET_PHOTO] || DEFAULT_BUCKET_PHOTO;
}

function getTableOccurrence(){
  return process.env[DEFAULT_ENV_DB_OCCURRENCE] || DEFAULT_DB_OCCURRENCE;
}
