service: aws-nodejs
provider:
  name: aws
  runtime: nodejs6.10
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

package:
  exclude:
    - src/**
    - node_modules/**
    - LICENSE
    - README.md
    - serverless.yml
    - .babelrc
    - .editorconfig
    - .eslintrc.json
    - .gitignore
    - serverless_old.yml
    - package-lock.json
    - npm-debug.log

functions:
  userNew:
    handler: dist/handler/v1/user.register
    events:
      - http:
          path: /v1/user/register
          method: post
          integration: aws_proxy
          cors: true

  userAuthenticate:
    handler: dist/handler/v1/user.authenticate
    events:
      - http:
          path: /v1/user/authenticate
          method: post
          integration: aws_proxy
          cors: true

  occurrenceRegister:
    handler: dist/handler/v1/occurrence.register
    events:
      - http:
          path: /v1/occurrence/register
          method: post
          integration: aws_proxy
          cors: true

  occurrenceDelete:
    handler: dist/handler/v1/occurrence.delete
    events:
      - http:
          path: /v1/occurrence/delete
          method: post
          integration: aws_proxy
          cors: true

  occurrenceList:
    handler: dist/handler/v1/occurrence.list
    events:
      - http:
          path: /v1/occurrence/list
          method: post
          integration: aws_proxy
          cors: true

resources:
  Resources:

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'User'
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 100
          WriteCapacityUnits: 100
    OccurrenceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'Occurrence'
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 100
          WriteCapacityUnits: 100
