service: aws-nodejs
provider:
  name: aws
  runtime: nodejs6.10

functions:
  user:
    handler: /handler/user.new
    events:
      - http:
          path: /user/new
          method: post
          integration: lambda
          cors: true

resources:
  Resources:

    #DYNAMODB
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(./config.js):location.tableUser}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    OcurrenceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(./config.js):location.tableOccurrence}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    #S3
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config.js):location.bucketPhoto}
